[package]
name = "game-probe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
directories = "4"
steamy-vdf = "0.2"
winreg = "0.50"
walkdir = "2"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
once_cell = "1"